### ISSUE TITLE
Add support for gallery-based websites

### ISSUE THREAD

**Issue by Bionus** [Bionus/imgbrd-grabber#917]
### Examples

* 4chan + derivates
* e-hentai.org + sad panda
* Fakku
* e-shuushuu
* Pixiv

### Implementation steps

**Basic**
* [x] Add posts parsing and sources, support only through gallery URLs
* [x] Clicking one of those galleries will open a new tab (see 1)
* [x] Add new "Gallery" tab type which is opened by clicking a gallery
* [x] Allow to download list of galleries
* [x] Allow to download individual galleries
* [x] Allow to download individual images from galleries
* [x] Gallery-specific tokens

**Nice to have**
* ~~Left clicking galleries must *not* open a new tab, but directly show this tab "inside" the current tab (same as the "Favorites" tab). Middle clicking must still open a new tab with the URL~~ killed as it is not coherent with images

**Gallery without thumbnails**
Moved to #1559

**Comment by brodycas3** [comment]
So is this also going to be a full-fledged browser for those sites too or only scrape images.

**Comment by Bionus** [comment]
Same as other sources, so if you consider them "full-fledged browser" then it will also be.

The only difference being that there will be another step: "list galleries, click gallery, list images, click image" (instead of "list images, click image").

**Comment by maskkulin** [comment]
Pixiv is missing

**Comment by brodycas3** [comment]
yes, Pixiv is the most major one. add it

**Comment by Bionus** [comment]
Moved to 5.5.0 or else 5.4.0 will not release any time soon.

As for Pixiv, the list given in the initial post are just examples, what will be actually added in 5.5.0 is very likely to be only 4chan as a proof-of-concept. Other sources will be added separately, see #738 for example for Pixiv (that issue will likely get more activity once gallery support is added, feel free to bump it then).

**Comment by Bionus** [comment]
Moving to milestone 5.6.0 to prioritize #995 which also requires deep changes.

**Comment by MasterPetrik** [comment]
> the list given in the initial post are just examples

@Bionus what about http://e-shuushuu.net/ from #483 ? 

And in this list of examples better to focus on Pixiv first, I guess everyone here wants the same.

**Comment by MrAndre96** [comment]
Do you on giving all the sources above by default support?

**Comment by Bionus** [comment]
Maybe not all of them from the get-go, but when I'll release the gallery system, I'll at least have support for Pixiv and EH.

To be honest, I already have a work-in-progress version for EH that's progressing pretty well. The files can be found [here](https://github.com/Bionus/imgbrd-grabber/tree/develop/release/sites/E-Hentai) and only work with the [nightly](https://github.com/Bionus/imgbrd-grabber/releases/tag/nightly) version. Lots of things don't work yet though (see the checklist of this issue).

**Comment by MrAndre96** [comment]
How do you access the gallery? couldnt find it in the latest version. Also e-hentai didn't came up in the source list after adding the folder and changing the .ts to .js of model.ts.

**Comment by Bionus** [comment]
Yes, you cannot just rename TS files into JS, this won't work. Since I don't think you want to install the bunch of stuff used for their transformation during Grabber's compilation, you can just use this:

https://es6console.com/

Make sure to select "TypeScript" on the left, copy/paste the contents of the TS file, then click "Transform", and you'll get the corresponding JS file on the right.

Otherwise, install NodeJS on your machine, download the repository, switch to the `develop` branch, go into the `release/sites` folder, then run `npm install` then `npm run build` and it'll work too.

Here's my locally built version for reference (in ZIP because GitHub won't let me upload JS files): [model.zip](https://github.com/Bionus/imgbrd-grabber/files/2346381/model.zip)
.

**Comment by MrAndre96** [comment]
It seems for me that the credential test always fails for e-hentai. Don't know how much of it has already being implemented since I did see a commit for the basic login

**Comment by panhartstuff** [comment]
May I suggest considering adding Twitter too? A lot of good artists now pretty much exclusively posts there, but Twitter's UI is a pain to navigate through

**Comment by Bionus** [comment]
An important note that was forgotten when writing this issue is the important of gallery-specific tokens when downloading gallery images:
* `%gallery_id%`
* `%gallery_name%`

Otherwise downloading multiple galleries at once generates a big mess in the downloads folder, with no way to distinguish galleries from each other.

**Comment by Bionus** [comment]
Information about the new "Galleries count as one" batch download setting (commit 134e5b3135849a2e9e3d39133188ffcc498659ad).

* It defaults to "true"
* When you set the "Images limit" to 20 and the search returns a page with 18 images, 1 gallery of 6 images, then 1 more image (for a total of 20 "results" on the page)
  * If set to "true", it will download the 18 first images, then the 6 images from the gallery, then the last image, resulting in a total of downloaded images of 25
  * If set to "false", it will download the 18 first image, then 2 images from the gallery, then stop because it reached the total of 20 downloaded images

In most cases, you'll want to leave it to "true".

**Comment by Bionus** [comment]
Basic Pixiv and E-Hentai support were pushed in the [nightly release](https://github.com/Bionus/imgbrd-grabber/releases/tag/nightly). There were also some heavy changes on batch downloads in order to support download of multiple galleries at once, so if you see anything funky, feel free to create a ticket.

Also note that E-H is pretty generous with temporary bans for over-use (which are 1~2h long), so make sure you put some healthy limits to it before using it too much.

> It seems for me that the credential test always displays failure althought it is a success. Don't know how much of it has already being implemented since I did see a commit for the basic login

Indeed. It seems that E-H has a 2-step login procedure, which isn't implemented in Grabber yet. I'll see how to do this properly then update E-H to have a proper login check.

**Comment by CharonM72** [comment]
Might this include Mastodon-based sites (such as Pawoo)? It's similar to Twitter in functionality, but I have no idea how (technically-speaking) it would be searched by something like Grabber.

**Comment by Bionus** [comment]
If there's an API or easily-parsable HTML results, it's possible. I suggest creating a separate issue however (like you did for Nije), and describe in which way you would download from that source.

**Comment by CharonM72** [comment]
Done. See #1521

**Comment by Bionus** [comment]
Most of the gallery support should now be done, so if you notice any bug with it, feel free to start opening issues (including issues to improve the support for the new sources).

The currently supported sources are (more might be added before release):
* Pixiv
* E-Hentai

New tokens:
* `name`: the name of the image/gallery (if relevant)
* `gallery.*`: where `*` is any kind of token from the gallery, usually `id` and `name`, but there might be more depending on the source

Given this change caused a lot of changes in public and private APIs, as well as some JSON formats, I might also bump the version number directly to `7.0.0` instead of `6.1.0`.

Known issues:
* Missing `gallery_position` / index token to name images according to their position in a gallery (issue #1552)
* Grabber reports `gallery.*` tokens as non-existing (issue #1552)
